"""post table

Revision ID: b40b6cb6d49c
Revises: e23dbc803f78
Create Date: 2023-11-12 14:27:28.841835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b40b6cb6d49c'
down_revision = 'e23dbc803f78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(length=2000), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('content')

    # ### end Alembic commands ###
